# Generated by Django 4.0.3 on 2022-04-08 14:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_remove_file_file_remove_profile_image_file_url_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='url',
            new_name='image_url',
        ),
    ]
